system:
  ip:
  port: 8080
  env: dev
  gin_mode: release
log:
  app: blogW_server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: wang
redis:
  addr: 127.0.0.1:6379
  password: 1234
  db: 2
db:
  user: root
  password: 12345678
  host: 127.0.0.1
  port: 3306
  db: blogW
  debug: false
  source: mysql
db1:
  user: root
  password: 12345678
  host: 127.0.0.1
  port: 3306
  db: blogW
  debug: false
  source: mysql