system:
  ip: ""
  port: 8080
  gin_mode: release
  env: dev
log:
  app: blogW_server
  dir: logs
db:
  user: root
  password: "12345678"
  host: 127.0.0.1
  port: 3306
  db: blogW
  debug: false
  source: mysql
db1:
  user: root
  password: "12345678"
  host: 127.0.0.1
  port: 3306
  db: blogW
  debug: false
  source: mysql
jwt:
  expire: 3
  secret: xxx
  issuer: wang
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: images001
site:
  siteInfo:
    title: 王佳阅博客1
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 王qi
    icon: /yyy.png
    webPath: uploads/index.html
  seo:
    keywords: 王qi
    description: 王佳阅
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
  login:
    qqLogin: false
    usernamePwdLogin: false
    emailLogin: false
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: true
email:
  domain: ""
  port: ""
  sendEmail: ""
  authCode: ""
  sendNickname: ""
  ssl: false
  tls: false
qq:
  appID: "34423"
  appKey: ""
  redirect: http://xxxx
qiNiu:
  enable: true
  accessKey: "AaHd2emsnXxdTKNaT0seDG2g-suxyA2vxQlz8_KV"
  secretKey: "2V28lm12d_ovemIuRNTTZPlua8vF5LYn-TQNP8IV"
  bucket: "wangqiyue0712"
  uri: https://svswmpyac.hn-bkt.clouddn.com
  region: z2
  prefix: blogW
  size: 3
  expire: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gshgsdh
  nickname: 小王
  avatar: /xxx/xxx
